  workflow_dispatch:
    inputs:
      language:
        description: 'Language'
        required: false
        type: string
      gate:
        description: 'Gate (compile or test)'
        required: false
        type: string
      buildcommand:
        description: 'Custom build command'
        required: false
        type: string
      testcommand:
        description: 'Custom test command'
        required: false
        type: string
